services:
  backend:
    build: .                # ✅ Current directory (notes-backend)
    container_name: notes-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  frontend:
    build: ../notes-frontend   # ✅ one level up, sibling folder
    container_name: notes-frontend
    ports:
      - "3000:80"
    restart: always
